<?php
	return array(
		'ai_filter' => 'Filter',
		'aisubmit' => 'Create',
		'copyp' => 'Copy Prompt',
		'generate' => 'Generate',
		'nfound' => 'You haven\'t added any posts to favorites yet.',
		'aiplace' => 'An Impressionist oil painting of sunflowers in a purple vase…',
		'ai_nprompt' => 'Negative prompt',
		'credits' => 'Credits',
		'nocredits' => 'You don\'t have enough credits to create ai images.',
		'buycredits' => 'Buy More!',
		'prvt' => 'Private',
		'pposts' => 'My private posts',
		'ppage' => 'Private post',
		'ppaget' => 'This post only visible to you!',
		'nfoundpp' => 'There is no private post',
		'widescreen' => 'Widescreen',
		'landscape' => 'Landscape',
		'square' => 'Square',
		'portrait' => 'Portrait',
		'vertical' => 'Vertical',
		'long' => 'Long',
		'aisizes' => 'Size',
		'sd' => 'Stable Diffusion',
		'odalle' => 'Open Dall-e',
		'pix' => 'PixArt',
		'proteus' => 'Proteus',
		'dreams' => 'DreamShaper',
		'oj' => 'Open Journey',
		'playg' => 'Playground',
		'de' => 'Dall-e',
		'realxl' => 'Realistic Vision',
		'de3' => 'Dall-e 3',
		'prompter' => 'AI Prompter',
		'sdn' => 'New Stable Diffusion'
	);